//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhan
    {
        public int MaPhieuNhan { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSP { get; set; }
        public int SoLuongNhap { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    }
}
