//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonLuong
    {
        public int MaHDLuong { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> SoGioLam { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
