//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public Nullable<System.DateTime> NgayGioTao { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<int> MaKM { get; set; }
        public string LoaiHoaDon { get; set; }
        public string MaHD { get; set; }
    }
}
