//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKM { get; set; }
        public string TenChuongTrinh { get; set; }
        public double GiaTriKhuyenMai { get; set; }
        public string DieuKienKhuyenMai { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int SoLuong { get; set; }
    }
}
